services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SQL_SERVER_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
      - ./backups:/var/opt/mssql/backups
    restart: unless-stopped

  app:
    build: .
    container_name: fourstory-web-api
    ports:
      - "8080:8080"
    environment:
      SQL_SERVER_USERNAME: ${SQL_SERVER_USERNAME}
      SQL_SERVER_PASSWORD: ${SQL_SERVER_PASSWORD}
      SQL_SERVER_TGAME_URL: ${SQL_SERVER_TGAME_URL}
      SQL_SERVER_TGLOBAL_URL: ${SQL_SERVER_TGLOBAL_URL}
    restart: unless-stopped

volumes:
  sqlserverdata: