global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: fourstory_web
    metrics_path: /actuator/prometheus
    static_configs:
        - targets: ['app:8080']
          labels:
            application: fourstory-web-api